# Generated by Django 2.1.15 on 2021-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='date_time_field',
            field=models.DateTimeField(unique=True),
        ),
    ]
