# Generated by Django 2.1.15 on 2021-05-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
    ]
