# Generated by Django 2.1.15 on 2021-05-07 07:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_advisor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.advisor_image_file_path),
        ),
    ]
