# Generated by Django 2.1.15 on 2021-05-07 12:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_advisor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='image',
            field=models.ImageField(upload_to=core.models.advisor_image_file_path),
        ),
    ]
