# Generated by Django 2.1.15 on 2021-05-10 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210510_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='bookingtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(blank=True, default="", null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
